### ISSUE TITLE
Performance comparison example for queueing_tool against C++, Ciw, and Simpy.

### ISSUE THREAD

**Issue by galenseilis** [djordon/queueing-tool#105]
I was reading the performance comparisons near the end of [Palmer *et al* 2017](https://arxiv.org/pdf/1710.03561.pdf). I realized they left out queueing_tool!

Here is a description of the model used in their comparisons:
> A model of an M/M/3 queue [41], with arrival rate λ = 10, and service rate μ = 4 was built in each
framework. The models were run for 800 time units, with a warmup time of 100 time units. The aim was to
find the average waiting time in the queue.

I've tried to adapt from the [`example_grocery_store`](https://github.com/djordon/queueing-tool/blob/master/examples/example_grocery_store.py), but I have to admit I find the nested dictionary pattern a bit obscure without an explicit explanation. It is possible that I have configured the adjacency or edge list incorrectly. Here is my (incorrect) attempt.

```python
import functools
import numpy as np
import queueing_tool as qt

# Define the parameters
arrival_rate = 10.0
service_rate = 4.0
num_servers = 3
sim_time = 800
warmup_time = 100

# Make an adjacency list
adjacency_list = {0: {1: {}}, 1:{}}

# Make an object that has the same dimensions as your adjacency list that
# specifies the type of queue along each edge.
edge_list = {0: {1: 1}}

# Create a networkx directed graph using the adjacency list and edge list
g = qt.adjacency2graph(adjacency=adjacency_list, edge_type=edge_list)

# Make a mapping between the edge types and the queue classes that sit on each
# edge. Do not use 0 as a key, it's used to map to NullQueues.
q_classes = {0:qt.NullQueue, 1:qt.QueueServer}

# Define the arrival and service functions
def arrival_rate_func(t):
    return arrival_rate

def service_rate_func(t):
    return service_rate

# Make a mapping between the edge types and the parameters used to make those
# queues.
q_args = {
    1: {'arrival_f': arrival_rate_func, 'service_f': service_rate_func, 'num_servers': num_servers},
}

# Put it all together to create the network
qn = qt.QueueNetwork(g=g, q_classes=q_classes, q_args=q_args)

# Set the maximum number of agents
qn.max_agents = np.inf

# Initialize the network
qn.initialize(edge_type=1)

# Data is not collected by default. This makes all queues collect data as the
# simulations take place.
qn.start_collecting_data()

# Simulate the network
qn.simulate(t=sim_time + warmup_time)

# Collect data
data = qn.get_queue_data()

# Calculate the average waiting time
average_waiting_time = data[1]['Wq'].mean()
print(f"Average waiting time in the queue: {average_waiting_time:.2f} time units")
```

I would appreciate assistance with learning how to configure this M/M/3 queue correctly.

**Comment by galenseilis** [comment]
I tried adapting from the [overview](https://queueing-tool.readthedocs.io/en/latest/overview.html) by assigning

```python
# Make an adjacency list
adja_list = {0: [1]}

# Make an object that has the same dimensions as your adjacency list that
# specifies the type of queue along each edge.
edge_list = {0: {}, 1:{}}
```

But that still doesn't seem to be right since it keeps going until I run out of memory.

**Comment by galenseilis** [comment]
There's nothing wrong with the queueing_tool documentation example. This runs fine:

```python
import queueing_tool as qt
import numpy as np

adja_list = {0: [1], 1: [k for k in range(2, 22)]}
edge_list = {0: {1: 1}, 1: {k: 2 for k in range(2, 22)}}
g = qt.adjacency2graph(adjacency=adja_list, edge_type=edge_list)

def rate(t):
    return 25 + 350 * np.sin(np.pi * t / 2)**2

def arr_f(t):
    return qt.poisson_random_measure(t, rate, 375)

def ser_f(t):
    return t + np.random.exponential(0.2 / 2.1)

q_classes = {1: qt.QueueServer, 2: qt.QueueServer}
q_args    = {
    1: {
        'arrival_f': arr_f,
        'service_f': lambda t: t,
        'AgentFactory': qt.GreedyAgent
    },
    2: {
        'num_servers': 1,
        'service_f': ser_f
    }
}

qn = qt.QueueNetwork(g=g, q_classes=q_classes, q_args=q_args, seed=13)

qn.start_collecting_data()
qn.initialize(edge_type=1)
qn.simulate(t=1.9)
```

**Comment by djordon** [comment]
I believe the issue lies with your arrival and service functions. They should be designed to take the current time as input and then return the next arrival or departure time, respectively. Here's how you might structure the arrival and service functions:

```python
LAMBDA = 1.0 / arrival_rate
MU = 1.0 / service_rate

def arrival_func(t):
    return t + np.random.exponential(LAMBDA)

def service_func(t):
    return t + np.random.exponential(MU)
```

Also, I believe your `edge_list` should be structured as follows:

```python
edge_list = {0: {1: 1}}
```

> I've attempted to adapt the code from the [example_grocery_store](https://github.com/djordon/queueing-tool/blob/master/examples/example_grocery_store.py). However, I must confess that I find the nested dictionary pattern somewhat perplexing without a clear explanation.

I understand your perspective. I recall considering a few different design approaches myself. Let me provide a brief explanation:

Queues are placed on edges, and we aim to specify the class and configuration for each queue within the network. I've adopted a format here similar of an adjacency list. In an adjacency list, the dictionary keys represent nodes, while their corresponding values are lists of other nodes. For our edge list, keys remain as nodes, but the values now become lists of node-edge type pairs. For instance, if the adjacency list looks like this:

```python
{0: [1, 2], 1: [2], 2: []}
```

The corresponding edge list would resemble:

```python
{0: [(1, t01), (2, t02)], 1: [(2, t12)], 2: []}

# which, in my view, is nearly equivalent to
{0: {1: t01, 2: t02}, 1: {2: t12}, 2: {}}
```
In the above, `txy` represents the edge type from node `x` to node `y`.

---

Hopefully this clarifies things a little. Also, I hope I solved the issue with your adaptation. If not I don't mind looking it over again to help out.

**Comment by galenseilis** [comment]
> I believe the issue lies with your arrival and service functions. They should be designed to take the current time as input and then return the next arrival or departure time, respectively. Here's how you might structure the arrival and service functions:
> 
> ```python
> LAMBDA = 1.0 / arrival_rate
> MU = 1.0 / service_rate
> 
> def arrival_func(t):
>     return t + np.random.exponential(LAMBDA)
> 
> def service_func(t):
>     return t + np.random.exponential(MU)
> ```
> 
> Also, I believe your `edge_list` should be structured as follows:
> 
> ```python
> edge_list = {0: {1: 1}}
> ```
> 
> > I've attempted to adapt the code from the [example_grocery_store](https://github.com/djordon/queueing-tool/blob/master/examples/example_grocery_store.py). However, I must confess that I find the nested dictionary pattern somewhat perplexing without a clear explanation.
> 
> I understand your perspective. I recall considering a few different design approaches myself. Let me provide a brief explanation:
> 
> Queues are placed on edges, and we aim to specify the class and configuration for each queue within the network. I've adopted a format here similar of an adjacency list. In an adjacency list, the dictionary keys represent nodes, while their corresponding values are lists of other nodes. For our edge list, keys remain as nodes, but the values now become lists of node-edge type pairs. For instance, if the adjacency list looks like this:
> 
> ```python
> {0: [1, 2], 1: [2], 2: []}
> ```
> 
> The corresponding edge list would resemble:
> 
> ```python
> {0: [(1, t01), (2, t02)], 1: [(2, t12)], 2: []}
> 
> # which, in my view, is nearly equivalent to
> {0: {1: t01, 2: t02}, 1: {2: t12}, 2: {}}
> ```
> 
> In the above, `txy` represents the edge type from node `x` to node `y`.
> 
> Hopefully this clarifies things a little. Also, I hope I solved the issue with your adaptation. If not I don't mind looking it over again to help out.

Thank you @djordon . That is very helpful. Here is the final state of the code:

```python
import functools
import numpy as np
import queueing_tool as qt

# Define the parameters
arrival_rate = 10.0
service_rate = 4.0
num_servers = 3
sim_time = 800
warmup_time = 100

LAMBDA = 1.0 / arrival_rate
MU = 1.0 / service_rate

# Make an adjacency list
adjacency_list = {0: {1: {}}, 1:{}}

# Make an object that has the same dimensions as your adjacency list that
# specifies the type of queue along each edge.
edge_list = {0: {1: 1}}

# Create a networkx directed graph using the adjacency list and edge list
g = qt.adjacency2graph(adjacency=adjacency_list, edge_type=edge_list)

# Make a mapping between the edge types and the queue classes that sit on each
# edge. Do not use 0 as a key, it's used to map to NullQueues.
q_classes = {0:qt.NullQueue, 1:qt.QueueServer}

# Define the arrival and service functions
def arrival_func(t):
    return t + np.random.exponential(LAMBDA)

def service_func(t):
    return t + np.random.exponential(MU)

# Make a mapping between the edge types and the parameters used to make those
# queues.
q_args = {
    1: {'arrival_f': arrival_func,
        'service_f': service_func,
        'num_servers': num_servers},
}

# Put it all together to create the network
qn = qt.QueueNetwork(g=g, q_classes=q_classes, q_args=q_args)

# Set the maximum number of agents
qn.max_agents = np.inf

# Initialize the network
qn.initialize(edge_type=1)

# Data is not collected by default. This makes all queues collect data as the
# simulations take place.
qn.start_collecting_data()

# Simulate the network
qn.simulate(t=warmup_time+sim_time)

# Collect data
data = qn.get_queue_data()

# Calculate the average waiting time
data = data[:,:2]
fin_data = data[data[:,1] > 0]
fin_wait = fin_data[:,1] - fin_data[:,0]
fin_wait.mean()
average_waiting_time = fin_wait.mean()
print(f"Average waiting time in the queue: {average_waiting_time:.2f} time units")
```

Let me know if there are any issues. The above should be computing the M/M/3 queue.

Looks like queuing_tool is faster **without** PyPy than either of Ciw or Simpy are **with** PyPy. And queueing_tool got a 2x speed improvement with PyPy. I'll run some more simulations and put them on my blog at some point.

I'll close the issue for now. Please open it again if you find that there is something incorrect with my implementation of a M/M/3 queue in queueing_tool.

Thank you for your assistance.

**Comment by djordon** [comment]
Nice! This setup looks right to me.

Another way to ensure we've set up this test correctly is by checking the number of events that occurred across all simulators. In queueing-tool, you can examine the `num_events` property of the `QueueNetwork`. This property increments with each arrival and departure throughout the entire network (which, in this case, is essentially a single M/M/3 queue). Ideally, the number of events should be roughly consistent across all three simulators. If there's a discrepancy, we might have made a configuration error.
