### ISSUE TITLE
AttributeError: 'DiGraph' object has no attribute 'new_vertex_property'

### ISSUE THREAD

**Issue by m-deck** [djordon/queueing-tool#46]
When attempting to run the line:

`g.new_vertex_property('pos')`

from [this link](http://queueing-tool.readthedocs.io/en/latest/overview.html), I am getting this error:

> AttributeError                            Traceback (most recent call last)
> <ipython-input-11-c9122040f700> in <module>()
> ----> 1 g.new_vertex_property('pos')
>       2 pos = {}
>       3 for v in qn.g.nodes():
>       4     if v == 0:
>       5         pos[v] = [0, 0.8]
> 
> AttributeError: 'DiGraph' object has no attribute 'new_vertex_property'

I am running Python 2.7.10 on macOS Sierra. Please let me know if you have any suggestions. I'm currently reviewing the [Graph docs](https://graph-tool.skewed.de/) to see how the inheritance from Graph to DiGraph is getting lost.

**Comment by m-deck** [comment]
I am now noticing that graph-tool and networkx are completely separate, and new_vertex_property doesn't seem to exist within networkx. Is there some conversion I might need to do in order to run the code?

**Comment by djordon** [comment]
Oh, I have a typo in the docs. It should read
```python
qn.g.new_vertex_property('pos')
```
I'll update the docs. Let me know if you still have any issues.

**Comment by djordon** [comment]
The docs were updated a while ago, specifically in https://github.com/djordon/queueing-tool/commit/03374782f5acec7b612dc84f17d251693c4c9c20.
