### ISSUE TITLE
cannot run in example

### ISSUE THREAD

**Issue by ZeyuLuan** [djordon/queueing-tool#60]
Hello, I run the example file named "example_grocery_store.py". On my Mac+VMware Fusion+ Ubuntu 16.04+python3.5 settings, it shows "AttributeError: 'QueueNetworkDiGraph' object has no attribute 'node'". Detailed information can be seen in the screen snap. Can anybody tell me how to fix this issue? Thanks!
![image](https://user-images.githubusercontent.com/28219641/68360678-f4dd0a80-015b-11ea-9c8a-7333cc9c3822.png)
<img width="1298" alt="截屏2019-11-07下午12 42 36" src="https://user-images.githubusercontent.com/28219641/68360726-1b02aa80-015c-11ea-93e3-d5eea27596ac.png">

**Comment by djordon** [comment]
Hey, sorry for the delayed response. I think I know what happened and come baring solutions.

The `QueueNetworkDiGraph` class subclasses `networkx.DiGraph` and expects there to be a node attribute. In your recent installation you probably installed Networkx 2.4, which was recently release. In that release the networkx folks [removed the `node` attribute](https://networkx.github.io/documentation/stable/release/release_2.4.html#deprecations) from graph objects, which broke this package.

So a short term solution is to install queueing-tool with a specific version of networkx. Sometime this weekend I'll release a new version of queueing-tool that fixes this.

**Comment by djordon** [comment]
@ZeyuLuan this should be fixed in queueing-tool 1.2.4. Let me know if you notice any other issues.

**Comment by ZeyuLuan** [comment]
Hello Daniel, it works now as shown in the screen shot. I wonder if I can query how many packets in each queue at each time step. Or it just shows the congestion states in a broad view? Thanks!





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Daniel Jordon"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月10日(星期天) 中午1:48
收件人:&nbsp;"djordon/queueing-tool"<queueing-tool@noreply.github.com&gt;;
抄送:&nbsp;"宇杰"<691485620@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [djordon/queueing-tool] cannot run in example (#60)




@ZeyuLuan this should be fixed in queueing-tool 1.2.4. Let me know if you notice any other issues.

**Comment by djordon** [comment]
> I wonder if I can query how many packets in each queue at each time step. Or it just shows the congestion states in a broad view?

The data that is stored is raw arrival and departure times. So you will be able to compute congestion over any time period that is of interest. Note that data collection needs to be enabled, and you can specify which queues you want to enable (by it's "all" of them).
