### ISSUE TITLE
Agents always served at time t (no queues or delays)

### ISSUE THREAD

**Issue by paulaceccon** [djordon/queueing-tool#63]
I'm using custom csvs to define both service and arrival rates. 
For arrival rate, I have something like: 

```
timestamp,number_of_vehicles
2020-01-01 00:00:00,26
2020-01-01 01:00:00,31
2020-01-01 02:00:00,26
2020-01-01 03:00:00,23
```

Which defines the number of vehicles that arrive per hour.
For service rate, I have: 

```
timestamp,time_in_place1,time_in_place2,time_in_place3,time_in_place4, ...
01/01/20 00:00,456.0,131.0,168.0,93.0, ...
01/01/20 01:00,404.0,111.0,286.0,92.0, ...
01/01/20 02:00,491.0,163.0,272.0,140.0, ...
01/01/20 03:00,442.0,148.0,463.0,91.0, ...
```

Which define the mean time (seconds) a vehicle stays at placex per hour.

I have defined, after some research, my arrival and service rates such as:

```
    # ------------------------------------------------------------------------------------------------------------------
    # Arrival rates
    # ------------------------------------------------------------------------------------------------------------------
    def arrival_rate(self, t):
        self.update_iteration(t)
        return t + 1 / self._arrival_rate_df.iloc[self._iteration]['number_of_vehicles']

    # ------------------------------------------------------------------------------------------------------------------
    # Service rates
    # ------------------------------------------------------------------------------------------------------------------
    def service_rate_order(self, t):
        self.update_iteration(t)
        return t + self._service_rate_df.iloc[self._iteration]['time_in_place1']
```

After creating my network with 6 nodes and simulating, however, no matter what I do with the rates, it seems that all agents are served as they arrive. With no delays or queues happening. Collecting the data, I have something like: 

```
          0      1      2    3    4     5
0      26.0   26.0   26.0  0.0  1.0   0.0
1      57.0   57.0   57.0  0.0  1.0   0.0
2      83.0   83.0   83.0  0.0  1.0   0.0
3     106.0  106.0  106.0  0.0  1.0   0.0
4     126.0  126.0  126.0  0.0  1.0   0.0
..      ...    ...    ...  ...  ...   ...
192   901.0    0.0    0.0  0.0  0.0  11.0
```

I wonder how this could be happening.

Another question that I have, is, given that I can correctly simulate what I need to, how do I validate the results? I know how many cars should arrive by hour and how long should they be in the system per hour. But, from the data obtained when collecting data, I cannot match agents to get the total time, per agent, spend in the system, for example.

@djordon, sorry to be opening an issue. I think it's more about me unable to figure it out how to use the tool properly, but any help would be appreciated.

**Comment by djordon** [comment]
@paulaceccon Oh wow, this is interesting. I honestly don't see how this could be happening, unless the queue that this is happening at is a misconfigured `QueueServer`.

Could you provide more info about your network setup? Specifically, how did you setup the `QueueServer` along edge zero (column 5 of the collected data shows which queue this happened at, and from what you have pasted above, it seems like the weirdness is happening at least at `QueueServer` zero). If I could setup basically what you have setup, it would be much easier for me to help out here.

**Comment by paulaceccon** [comment]
Could I contact you via email? I can't publish the data here.

**Comment by djordon** [comment]
Yeah definitely, shoot me an email. My address is:
https://github.com/djordon/queueing-tool/blob/00fc1b88257faeb2a31be75040b6649603460bab/setup.py#L88
