### ISSUE TITLE
Changing the number of servers in Queueserver not compatible with a non-empty queue

### ISSUE THREAD

**Issue by jeroenburgt** [djordon/queueing-tool#64]
Changing the number of servers does not work properly when the queue of the server is not empty. This does not work for increasing or decreasing the amount of servers:

1. Increasing the amount of servers:
- When departures occur and there is a queue, an agent is from the queue is placed in service. However, this will only make sure that already existing servers are being occupied, this will never put an agent in a newly created server (when there is a queue)
- When an arrivals occurs and the queue is empty, it is added to the new severs because the following logic is used in next_event: Add arrival to departures list if self.num_system <= self.num_servers: When the queue is empty this is always true. However, when there are agents in the queue, this logic fails. Furthermore, when there is a queue, we want the agents in the front of the queue to be added to the newly created servers, not the new arrivals.

2. Decreasing the amount of servers:
- When departures occur, an agent is from the queue is placed in service. So existing servers will always stay occupied, even when the number of servers is reduced as this is not checked.
- When new arrivals occur and there is a queue, the arrivals are placed in the queue. So this will never reduce the amount of people in service.

Suggested solution:

Increasing the amount of severs:
- Add agents from the queue to the new servers at the time when increasing the amount of servers.
This can be done by added the following code to the function `set_num_severs(self, n)`

```
            if n > self.num_servers:
                for i in range(n - self.num_servers):
                    if len(self.queue) > 0:
                        agent = self.queue.popleft()
                        if self.collect_data and agent.agent_id in self.data:
                            self.data[agent.agent_id][-1][1] = self._current_t

                        agent._time = self.service_f(self._current_t)
                        agent.queue_action(self, 1)
                        heappush(self._departures, agent)
                        self._update_time()
```

Decreasing the amount of servers:
- Add a check on the number of agents in service versus the amount of severs in the function `next_event(self):` when processing a departure.

`if len(self.queue) > 0 & (self.num_system + 1 - len(self.queue)) < self.num_servers:`

I have added my updated code for reference:
[queue_servers.zip](https://github.com/djordon/queueing-tool/files/4305170/queue_servers.zip)

**Comment by djordon** [comment]
Great find, and thanks for opening an issue about this. You're right on both counts and I agree with the logic motivating your solutions to both issues. I'll open a PR addressing these issue in the next few days with implementations that will mirror most of what you have above, assuming someone doesn't don't beat me to it.
