### ISSUE TITLE
QueueServer.clear() can use predefined deque.clear()

### ISSUE THREAD

**Issue by michalplat** [djordon/queueing-tool#68]
In `QueueServer` class method `clear` is defined as follows:

```python
    def clear(self):
        """Clears out the queue. Removes all arrivals, departures, and
        queued agents from the :class:`.QueueServer`, resets
        ``num_arrivals``, ``num_departures``, ``num_system``, and the clock to
        zero. It also clears any stored ``data`` and the server is then
        set to inactive.
        """
        self.data = {}
        self._num_arrivals = 0
        self._oArrivals = 0
        self.num_departures = 0
        self.num_system = 0
        self._num_total = 0
        self._current_t = 0
        self._time = infty
        self._next_ct = 0
        self._active = False
        self.queue = collections.deque()
        inftyAgent = InftyAgent()
        self._arrivals = [inftyAgent]
        self._departures = [inftyAgent]
```

In line  ` self.queue = collections.deque()`, I would rather use `self.queue.clear()`, as it's [already implemented](https://docs.python.org/3.7/library/collections.html#collections.deque.clear) in `collections.deque`.
I'll show user scenario where this approach would be more user-friendly. Let's say I overwrite `self.queue` attr:

```python
class MyQueueServer(qt.QueueServer):
    def __init__(self, some_custom_argument, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.queue = MyQueue(some_custom_argument)
``` 
If in `QueueServer.clear` it would be `self.queue.clear()` I could make sure that MyQueue object has `clear` method and it would be end of the work, for now I have to override whole `QueueServer.clear` to make it works in my way. It's not big deal, but if someone else overwrite `self.queue`, he may be wondering why his custom `self.queue` is gone after clearing.

**Comment by djordon** [comment]
Oh right! My appologies, I forgot about this when I commented on custom queues in https://github.com/djordon/queueing-tool/issues/67#issuecomment-723521324.

I think it's a good idea to easily allow people to specify the queue class and doing so should be relatively straightforward. Also, this can be a done in a backwards compatible way. Thanks for calling this out, I'll slot this in when I have more time to release a new version.
