### ISSUE TITLE
Error using draw() and animate() functions

### ISSUE THREAD

**Issue by arsiboo** [djordon/queueing-tool#74]
I'm trying to use draw() and animate() functions, however both functions raise the same error which is: 

"AttributeError: 'LineCollection' object has no property 'offset_position'"

I have followed all the requirements in documentation and I use Python 3.7.

Would you please help me fix this issue?

Thanks

**Comment by djordon** [comment]
Nuts. 

Hmmm, what version of `matplotlib` is installed? My best guess is that later versions of matplotlib removed the `offset_position` argument from either their `matplotlib.collections.LineCollection` or `matplotlib.collections.Collection` objects (a quick peek at their latest docs confirms this).

The version of matplotlib that queueing-tool was designed around is 1.5.x, which is much older than the version currently available, 3.5.x. The quick fix for this is to downgrade your installed version of matplotlib to 1.5.1 (which is a crappy solution that I don't like at all). A proper fix involves cutting a new release to make queueing-tool less opinionated on the arguments of `LineCollection`. I'm not opposed to that, it's just difficult to find the time to cut such a release. I'll try to update this issue with a time estimate "soon".

**Comment by arsiboo** [comment]
Thank you so much for the quick solution. I downgraded matplotlib and it works now.

**Comment by djordon** [comment]
Okay I think I can have an official fix out for this this week.

**Comment by djordon** [comment]
The new version of queueing-tool is up (https://pypi.org/project/queueing-tool/).
