### ISSUE TITLE
Citing

### ISSUE THREAD

**Issue by arsiboo** [djordon/queueing-tool#92]
Hi

How can one cite queueing-tool in a publication?

Thank you

**Comment by djordon** [comment]
That's a good question. I remember looking into this long ago but don't quite remember why I didn't write this up in the README, let me look into this again and get back to you.

**Comment by arsiboo** [comment]
Hi, may I know if there are any recommendations?

**Comment by djordon** [comment]
> Hi, may I know if there are any recommendations?

None at the moment. I think I remember what happened: way back when, I arrived at the conclusion that I would need to "publish" this software and I didn't want to take the time and energy to do that. Now a days I think I can just publish this at https://zenodo.org and be done with it. Let me take 30 minutes to do this now and report back.

**Comment by djordon** [comment]
Okay, I was able to setup this repository on zenodo for citing. Now there should be a little drop-down at the repository homepage that says "Cite this Repository" where you can get citation info. Here is the current bibtex item:
```bibtex
@software{Jordon_Queueing-tool_a_queueing_2023,
    author = {Jordon, Daniel},
    doi = {10.5281/zenodo.8057970},
    month = jun,
    title = {{Queueing-tool: a queueing network simulator}},
    url = {https://github.com/djordon/queueing-tool},
    version = {v1.2.5},
    year = {2023}
}
```
Hope this helps!

**Comment by arsiboo** [comment]
Awesome, thank you
